backend:
  build: ./
  links:
    - redis
    - influxdb
  ports: 
    - "8080:8080"
  restart: on-failure

redis:
  image: redis
  ports:
    - "6379"

influxdb:
  image: influxdb
  ports:
    - "8086"